// (c) 2021 Copyright, Real-Time Innovations, Inc.  All rights reserved.
// No duplications, whole or partial, manual or electronic, may be made
// without express written permission.  Any such copies, or revisions thereof,
// must display this notice unaltered.
// This code contains trade secrets of Real-Time Innovations, Inc.

const string PROXIMITY_DATA_TOPIC_NAME = "Proximity Data Topic";

const unsigned long SENSOR_ID_MAX_LENGTH = 16;
struct ProximityData {

    @key string<SENSOR_ID_MAX_LENGTH> sensor_id;
    float proximity;
};